#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RefreshLayout.Droid.Resource", IsApplication=true)]

namespace RefreshLayout.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int black = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int white = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int app_bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int item_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int refresh_arrow_down = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int refresh_arrow_up = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int xlistview_arrow = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int indicator = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int linear_root = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int progress = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int refresh_hint = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int refresh_root = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int refresh_time = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int scroll_view_root = 2131099649;
			
			// aapt resource value: 0x7f06000b
			public const int xlistview_footer_arrow = 2131099659;
			
			// aapt resource value: 0x7f060007
			public const int xlistview_footer_content = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int xlistview_footer_hint_textview = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int xlistview_footer_progressbar = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int xlistview_footer_text = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int xlistview_footer_time = 2131099658;
			
			// aapt resource value: 0x7f060011
			public const int xlistview_header_arrow = 2131099665;
			
			// aapt resource value: 0x7f06000d
			public const int xlistview_header_content = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int xlistview_header_hint_textview = 2131099663;
			
			// aapt resource value: 0x7f060012
			public const int xlistview_header_progressbar = 2131099666;
			
			// aapt resource value: 0x7f06000e
			public const int xlistview_header_text = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int xlistview_header_time = 2131099664;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int refresh_top_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int XListViewFooter = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int XListViewHeader = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int app_name = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int hello = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int refresh_down_text = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int refresh_release_text = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int toast_text = 2131034118;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RefreshableView;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
